services:

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./frontend/incassi
      dockerfile: Dockerfile
    restart: unless-stopped

  db:
    image: postgres:16.3-alpine3.20
    env_file:
      - .docker/pg_conf.env
    restart: unless-stopped
