services:

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped

  web:
    build:
      context: ./frontend/incassi
      dockerfile: Dockerfile
    restart: unless-stopped
