services:

  django:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    command: |
      bash -c
      "
        ./manage.py makemigrations && \
        ./manage.py migrate && (./manage.py createsuperuser --noinput || true)
        ./manage.py runserver 0.0.0.0:8000
      "
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/app/
      - static_volume:/app/static
    restart: unless-stopped
    env_file:
      - .docker/superuser_conf.env
      - .docker/django_secret_key.env

  web:
    build:
      context: ./frontend/incassi
      dockerfile: Dockerfile
    restart: unless-stopped

volumes:
  static_volume:
