"""empty message

Revision ID: e00c799a0640
Revises: 369caae98c4c
Create Date: 2025-06-15 20:30:17.179437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e00c799a0640"
down_revision: Union[str, None] = "369caae98c4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incasso", "media_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incasso", "media_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
