"""empty message

Revision ID: 89cfe64c9d95
Revises: d4f5c736131b
Create Date: 2025-11-01 15:04:34.890003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89cfe64c9d95"
down_revision: Union[str, None] = "d4f5c736131b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "id_payment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment",
        sa.Column("id_payment", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
