"""empty message

Revision ID: 7a326e0dfc03
Revises: 096ba10f2137
Create Date: 2025-03-22 18:28:51.417055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a326e0dfc03"
down_revision: Union[str, None] = "13c8cf8c6455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("document_document_id_fkey", "document", type_="foreignkey")
    op.drop_column("document", "document_id")
    op.add_column("incasso", sa.Column("document_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "incasso", "document", ["document_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incasso", type_="foreignkey")
    op.drop_column("incasso", "document_id")
    op.add_column(
        "document",
        sa.Column("document_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "document_document_id_fkey",
        "document",
        "document",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
