"""empty message

Revision ID: e7dba9a0ccfb
Revises: e00c799a0640
Create Date: 2025-07-05 16:58:48.833047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7dba9a0ccfb"
down_revision: Union[str, None] = "e00c799a0640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("incasso_media_id_key"), "incasso", type_="unique")
    op.drop_constraint(op.f("incasso_media_id_fkey"), "incasso", type_="foreignkey")
    op.drop_column("incasso", "media_id")
    op.add_column("media", sa.Column("incasso_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "media", "incasso", ["incasso_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "media", type_="foreignkey")
    op.drop_column("media", "incasso_id")
    op.add_column(
        "incasso",
        sa.Column("media_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("incasso_media_id_fkey"), "incasso", "media", ["media_id"], ["id"]
    )
    op.create_unique_constraint(
        op.f("incasso_media_id_key"),
        "incasso",
        ["media_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_table(
        "document",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "creation_date",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("image_path_list", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("incasso_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["incasso_id"],
            ["incasso.id"],
            name=op.f("document_incasso_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("document_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_pkey")),
    )
    # ### end Alembic commands ###
