"""empty message

Revision ID: 00bdb0065867
Revises: 948f7c88a552
Create Date: 2025-03-23 14:36:19.534516

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "00bdb0065867"
down_revision: Union[str, None] = "948f7c88a552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_incasso_id_fkey", "payment", type_="foreignkey")
    op.create_foreign_key(
        None, "payment", "incasso", ["incasso_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.create_foreign_key(
        "payment_incasso_id_fkey", "payment", "incasso", ["incasso_id"], ["id"]
    )
    # ### end Alembic commands ###
