"""empty message

Revision ID: 948f7c88a552
Revises: 9a458c2f351c
Create Date: 2025-03-23 12:40:20.244683

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "948f7c88a552"
down_revision: Union[str, None] = "9a458c2f351c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
