"""empty message

Revision ID: 369caae98c4c
Revises: 170afcb2bf44
Create Date: 2025-06-15 18:51:31.846913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "369caae98c4c"
down_revision: Union[str, None] = "170afcb2bf44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pdf_path", sa.String(), nullable=False),
        sa.Column(
            "type_of_media",
            sa.Enum("envelope", "scan", name="typeofmedia"),
            server_default="envelope",
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("incasso", sa.Column("media_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "incasso", ["media_id"])
    op.create_foreign_key(None, "incasso", "media", ["media_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incasso", type_="foreignkey")
    op.drop_constraint(None, "incasso", type_="unique")
    op.drop_column("incasso", "media_id")
    op.drop_table("media")
    # ### end Alembic commands ###
