"""empty message

Revision ID: e8356367513e
Revises:
Create Date: 2025-03-22 17:45:54.964783

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e8356367513e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
