"""empty message

Revision ID: 170afcb2bf44
Revises: 00bdb0065867
Create Date: 2025-04-08 15:35:08.838514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '170afcb2bf44'
down_revision: Union[str, None] = '00bdb0065867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    type_of_payment = sa.Enum('check', 'cash', name='typeofpayment')
    type_of_payment.create(op.get_bind())

    op.drop_column('incasso', 'type_of_payment')
    op.add_column('payment', sa.Column('id_payment', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('type_of_payment', type_of_payment, server_default="check", nullable=False))
    op.add_column('payment', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('payment', sa.Column('client_code', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment', 'client', ['client_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'client_code')
    op.drop_column('payment', 'amount')
    op.drop_column('payment', 'type_of_payment')
    op.drop_column('payment', 'id_payment')
    op.add_column('incasso', sa.Column('type_of_payment', postgresql.ENUM('check', 'cash', name='typeofincasso'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
