"""empty message

Revision ID: 7feede15a7da
Revises:
Create Date: 2025-02-27 22:26:14.268276

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7feede15a7da"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
