"""empty message

Revision ID: 9ddbe19174d1
Revises: 7feede15a7da
Create Date: 2025-02-27 22:27:31.592262

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9ddbe19174d1"
down_revision: Union[str, None] = "7feede15a7da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
