name: 'Docker Login'
description: 'Execute docker login and docker buildx setup'

inputs:
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}